# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  - name: dockerRegistryServiceConnection
    value: anchoredemo
    #value: 'c6337cf5-2e7b-4db4-b4a1-0d0d7cc18bb9'
  - name: imageRepository
    value: 'todoapi'
  - name: containerRegistry
    value: 'anchoredemo.azurecr.io'
  - name: dockerfilePath
    value: 'Dockerfile'
  - name: tag
    value: '$(Build.BuildId)'

  # Agent VM image name
  - name: vmImageName
    value: 'ubuntu-latest'

  # Anchore stuff
  - name: anchoreUser
    value: 'admin'
  - name: anchoreUrl
    value: 'http://168.61.69.162/v1/'
  - group: AnchoreCreds

stages:
- stage: Staging
  displayName: Build and push stage
  jobs:
  - job: Staging
    displayName: Staging
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

- stage: Scan
  displayName: Build and push stage
  jobs:
  - job: Scan
    displayName: Scan
    pool:
      name: 'Default'
    steps:
    - task: AnchoreEnterprise@0
      inputs:
        image: '$(containerRegistry)/$(imageRepository):$(tag)'
        url: $(anchoreUrl)
        username: $(anchoreUser)
        password: $(anchorepass)
