####
#
# Azure Pipeline for Todo API Server
#
# Displays usage of the Anchore integration with Azure DevOps
# 
####

trigger:
- master

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  - name: acrProdServiceConnection
    value: demoProduction
  - name: prodRegistry
    value: 'anchoredemo.azurecr.io'

  - name: acrStagingServiceConnection
    value: demoStaging
  - name: stagingRegistry
    value: 'demostaging.azurecr.io'

  - name: imageRepository
    value: 'todoapi'
  - name: dockerfilePath
    value: 'Dockerfile'
  - name: tag
    value: '$(Build.BuildId)'

  # Agent VM image name
  - name: vmImageName
    value: 'ubuntu-latest'

  # Anchore stuff
  - name: anchoreUser
    value: 'admin'
  - name: anchoreUrl
    value: 'http://168.61.69.162/v1/'
  - group: AnchoreCreds
    # anchorepass ^

stages:
- stage: Staging
  displayName: Build and push to staging registry
  jobs:
  - job: Staging
    displayName: Staging
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(acrStagingServiceConnection)
        tags: |
          $(tag)

- stage: Scan
  displayName: Scan the staged image
  dependsOn: Staging
  jobs:
  - job: Scan
    displayName: Scan
    pool:
      name: 'Default'
    steps:
    - task: AnchoreEnterprise@0
      inputs:
        image: '$(stagingRegistry)/$(imageRepository):$(tag)'
        url: $(anchoreUrl)
        username: $(anchoreUser)
        password: $(anchorepass)

- stage: Production
  displayName: Push to production registry
  dependsOn: Scan
  jobs:
  - job: Production
    displayName: Production
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(acrProdServiceConnection)
        tags: |
          $(tag)

# TODO: Deploy Application
