####
#
# Azure Pipeline for Todo API Server
#
# Displays usage of the Anchore integration with Azure DevOps
#
#####

trigger:
- master
- dev

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  - name: acrProdServiceConnection
    value: demoProduction
  - name: prodRegistry
    value: 'anchoredemo.azurecr.io'

  - name: acrStagingServiceConnection
    value: demoStaging
  - name: stagingRegistry
    value: 'demostaging.azurecr.io'

  - name: imageRepository
    value: 'todoapi'
  - name: dockerfilePath
    value: 'Dockerfile'
  - name: tag
    value: '$(Build.BuildId)'
  - name: prodImage
    value: '$(prodRegistry)/$(imageRepository)'

  - name: stagedImage
    value: '$(stagingRegistry)/$(imageRepository)'

  # Agent VM image name
  - name: vmImageName
    value: 'ubuntu-latest'

  # Anchore stuff
  - name: anchoreUser
    value: 'admin'
  - name: anchoreUrl
    value: 'http://23.100.36.77/v1/'
  - group: AnchoreCredentials
    # anchorepass ^

###########################################################

stages:

#
# Stage 1 - Staging
#
- stage: Staging
  displayName: Build and push to staging registry
  jobs:
  - job: Staging
    displayName: Staging
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: login
        containerRegistry: $(acrStagingServiceConnection)
        addPipelineData: false

    - script: |
        DOCKER_BUILDKIT=1 docker build -t $(stagedImage):$(tag) .
        docker tag $(stagedImage):$(tag) $(stagedImage)-task:$(tag)
        docker tag $(stagedImage):$(tag) $(stagedImage)-anchorecli:$(tag)
        docker push $(stagedImage):$(tag)
        docker push $(stagedImage)-task:$(tag)
        docker push $(stagedImage)-anchorecli:$(tag)

#
# Stage 2 - Scanning
#
- stage: TaskScan
  displayName: Anchore Enterprise Task Scan
  dependsOn: Staging
  jobs:
  - job: Scan
    displayName: Anchore Enterprise Task Scan
    pool:
      vmImage: $(vmImageName)
    steps:
    - script: |
        python3 -m pip install --upgrade pip setuptools wheel
        pip3 install --upgrade anchorecli
        echo "##vso[task.prependpath]$(HOME)/.local/bin"
      displayName: Install tools for Anchore CLI

    - task: AnchoreEnterprise@0
      inputs:
        image: '$(stagedImage)-task:$(tag)'
        url: $(anchoreUrl)
        username: $(anchoreUser)
        password: $(anchorepass)
        dockerfile: Dockerfile

#
# Stage 3 - Scanning
#
- stage: AnchoreCLI
  displayName: Anchore CLI Scan
  dependsOn: Staging
  jobs:
  - job: Scan
    displayName: Anchore CLI Scan
    pool:
      vmImage: $(vmImageName)
    steps:
    - script: |
        python3 -m pip install --upgrade pip setuptools wheel
        pip3 install --upgrade anchorecli
        echo "##vso[task.prependpath]$(HOME)/.local/bin"
        echo "##vso[task.setvariable variable=ANCHORE_CLI_USER]$(anchoreUser)"
        echo "##vso[task.setvariable variable=ANCHORE_CLI_PASS]$(anchorepass)"
        echo "##vso[task.setvariable variable=ANCHORE_CLI_URL]$(anchoreUrl)"
      displayName: Install tools for Anchore CLI

    - script: |
        echo "Scanning " $(stagedImage)-anchorecli:$(tag)
        anchore-cli image add '$(stagedImage)-anchorecli:$(tag)'
        anchore-cli image wait '$(stagedImage)-anchorecli:$(tag)'
        anchore-cli evaluate check '(stagedImage)-anchorecli:$(tag)'
      displayName: Scan using anchore-cli

#
# Stage 4 - Scanning
#
- stage: InlineScan
  displayName: Inline Scan
  jobs:
  - job: Scan
    displayName: Inline Scan
    pool:
      vmImage: $(vmImageName)
    steps:
    - script: |
        DOCKER_BUILDKIT=1 docker build -t $(imageRepository):inlinescan .
      displayName: Build the local image

    - script: |
        docker image ls
        curl -s https://ci-tools.anchore.io/inline_scan-v0.7.0 | bash -s -- \
          analyze \
          -u $(anchore_user) \
          -p $(anchorepass) \
          -r $(anchore_url) \
          -f ./Dockerfile \
          -g $(imageRepository):inlinescan
      displayName: Scan image and send to engine

    - script: |
        python -m pip install --upgrade pip setuptools wheel
        pip install --upgrade anchorecli
        echo "##vso[task.prependpath]${PATH}:/home/vsts/.local/bin"
        echo "##vso[task.setvariable variable=ANCHORE_CLI_USER]$(anchoreUser)"
        echo "##vso[task.setvariable variable=ANCHORE_CLI_PASS]$(anchorepass)"
        echo "##vso[task.setvariable variable=ANCHORE_CLI_URL]$(anchoreUrl)"
      displayName: Configure anchore-cli

    - script: |
        anchore-cli \
          --u $(anchore_user) \
          --p $(anchorepass) \
          --url $(anchore_url) \
          evaluate check localbuild/$(imageRepository):inlinescan
      displayName: Evaluate the image
