
trigger:
  - master
  - dev

variables:
  image_name: 'localbuild/testimage:ci'

stages:
- stage: Staging
  displayName: Build and push to staging registry
  jobs:
  - job: Staging
    displayName: Staging
    steps:
    - script: |
        docker build -t "$(image_name)" -f Dockerfile .

    - task: Anchore@0
      inputs:
        image: $(image_name)
        customPolicyPath: '.anchore/policy.json'
        anchoreVersion: 'v0.8.0'
        dockerfile: Dockerfile
        failBuild: false
        includeAppPackages: true

    - script: |
        echo $(policyStatus)

        echo $(billOfMaterials)
        cat $(billOfMaterials)

        echo $(vulnerabilities)
        cat $(vulnerabilities)
