
trigger:
  - master
  - dev

variables:
  image_name: "localbuild/testimage"
  tag: "ci"

stages:
- stage: Staging
  displayName: Build and push to staging registry
  jobs:
  - job: Staging
    displayName: Staging
    steps:

    - task: Docker@2
      inputs:
        command: build
        repository: "$(image_name)"
        tags: "$(tag)"

    - task: Anchore@0
      inputs:
        image: "$(image_name):$(tag)"
        anchoreVersion: "v0.8.0"
        dockerfile: Dockerfile
        failBuild: false
        includeAppPackages: true

    - script: |
        echo $(policyStatus)

        echo $(billOfMaterials)
        cat $(billOfMaterials)

        echo $(vulnerabilities)
        cat $(vulnerabilities)
