
trigger:
  - master
  - dev

stages:
- stage: Staging
  displayName: Build and push to staging registry
  jobs:
  - job: Staging
    displayName: Staging
    steps:
    - script: |
        docker build -t localbuild/testimage:ci -f Dockerfile .

    - task: Anchore@0
      inputs:
        image: 'localbuild/testimage:ci'
        customPolicyPath: '.anchore/policy.json'
        anchoreVersion: 'v0.8.0'
        dockerfile: Dockerfile
        failBuild: false
        includeAppPackages: true

    - script: |
        echo $(policyStatus)

        echo $(billOfMaterials)
        cat $(billOfMaterials)

        echo $(vulnerabilities)
        cat $(vulnerabilities)
