apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoapi
  template:
    metadata:
      labels:
        app: todoapi
    spec:
      containers:
      - name: todoapi
        image: anchoredemo.azurecr.io/todoapi
        ports:
        - containerPort: 9000
        volumeMounts:
        - mountPath: "/mnt/data"
          name: volume
      volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: todoapi-disk
